/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Pacific Aurora API
 * Canonical contract for Pacific Aurora. The frontend and backend are both
 * built against this single artifact.
 *
 * Rules encoded here:
 * - All ids are opaque strings. All timestamps are ISO-8601 UTC strings.
 * - `{ data: ... }` on success, `{ error: { code, message, details?, requestId? } }`
 *   on failure. HTTP failures are never returned as a 200.
 * - Attempting to read or modify another user's data returns 404, never 403,
 *   so a cross-user request is indistinguishable from a missing one.
 * - Sign-in failures return one uniform code and message.
 * - OTP resend is rate-limited to once per 2 minutes (429 with Retry-After: 120).
 * - `places.status`, `items.status` and `relationship_type` are free text; the
 *   named options in the UI are presets and manual entry is always allowed.
 *   `character_status` is the only true enum.
 * - A world holds at most 10 custom entity types.
 *
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Register with email and password, sending a verification OTP
 */
export const postAuthSignupBodyPasswordMin = 8;



export const PostAuthSignupBody = zod.object({
  "email": zod.email(),
  "password": zod.string().min(postAuthSignupBodyPasswordMin)
})

export const PostAuthSignupResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary Verify the signup OTP
 */
export const PostAuthOtpVerifyBody = zod.object({
  "email": zod.email(),
  "otp": zod.string()
})

export const PostAuthOtpVerifyResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary Resend the verification OTP (same generator)
 */
export const PostAuthOtpResendBody = zod.object({
  "email": zod.email().optional()
})

export const PostAuthOtpResendResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary Sign in with email or userid plus password
 */
export const PostAuthSigninBody = zod.object({
  "identifier": zod.string().describe('Email address or userid'),
  "password": zod.string()
})

export const PostAuthSigninResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary Sign in or sign up with Google
 */
export const PostAuthGoogleBody = zod.object({
  "credential": zod.string().describe('Google ID token')
})

export const PostAuthGoogleResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary Request a password-reset OTP; the response is uniform whether or not the account exists
 */
export const PostAuthForgotPasswordBody = zod.object({
  "email": zod.email()
})

export const PostAuthForgotPasswordResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary Reset the password using the OTP as the entry token
 */
export const postAuthPasswordResetBodyNewPasswordMin = 8;



export const PostAuthPasswordResetBody = zod.object({
  "email": zod.email(),
  "otp": zod.string(),
  "newPassword": zod.string().min(postAuthPasswordResetBodyNewPasswordMin)
})

export const PostAuthPasswordResetResponse = zod.object({
  "data": zod.unknown().optional()
})


/**
 * @summary End the session
 */
export const PostAuthLogoutResponse = zod.void()


/**
 * @summary The current session's user and profile, used to decide routing
 */
export const GetAuthSessionResponse = zod.object({
  "data": zod.object({
  "user": zod.object({
  "id": zod.string().optional(),
  "email": zod.email().nullish()
}).optional(),
  "profile": zod.object({
  "id": zod.string().optional(),
  "username": zod.string().nullish(),
  "userId": zod.string().nullish(),
  "onboardingComplete": zod.boolean().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}).optional()
}).optional()
})


/**
 * @summary The current user's profile
 */
export const GetProfilesMeResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "username": zod.string().nullish(),
  "userId": zod.string().nullish(),
  "onboardingComplete": zod.boolean().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}).optional()
})


/**
 * @summary Update username and/or userid; userid is unique; cleared userid keeps the completion flag raised
 */
export const PatchProfilesMeBody = zod.object({
  "username": zod.string().optional(),
  "userId": zod.string().optional()
})

export const PatchProfilesMeResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "username": zod.string().nullish(),
  "userId": zod.string().nullish(),
  "onboardingComplete": zod.boolean().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}).optional()
})


/**
 * @summary List the current user's worlds, most recently opened first
 */
export const GetWorldsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
})).optional()
})


/**
 * @summary Create a world
 */



export const PostWorldsBody = zod.object({
  "name": zod.string().min(1)
})

export const PostWorldsResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary Get a world
 */
export const GetWorldsWorldIdParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary Rename a world
 */
export const PatchWorldsWorldIdParams = zod.object({
  "worldId": zod.string()
})




export const PatchWorldsWorldIdBody = zod.object({
  "name": zod.string().min(1).optional()
})

export const PatchWorldsWorldIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary Delete the world and everything in it, including linked books
 */
export const DeleteWorldsWorldIdParams = zod.object({
  "worldId": zod.string()
})

export const DeleteWorldsWorldIdResponse = zod.void()


/**
 * @summary Mark the world as most recently opened
 */
export const PostWorldsWorldIdOpenParams = zod.object({
  "worldId": zod.string()
})

export const PostWorldsWorldIdOpenResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary List books in a world
 */
export const GetWorldsWorldIdBooksParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdBooksResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
})).optional()
})


/**
 * @summary Create a book; if it has no chapters, an "Introduction" chapter is created
 */
export const PostWorldsWorldIdBooksParams = zod.object({
  "worldId": zod.string()
})




export const PostWorldsWorldIdBooksBody = zod.object({
  "name": zod.string().min(1)
})

export const PostWorldsWorldIdBooksResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary Get a book
 */
export const GetBooksBookIdParams = zod.object({
  "bookId": zod.string()
})

export const GetBooksBookIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary Rename a book
 */
export const PatchBooksBookIdParams = zod.object({
  "bookId": zod.string()
})




export const PatchBooksBookIdBody = zod.object({
  "name": zod.string().min(1).optional()
})

export const PatchBooksBookIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary Delete the book's text and chapters; world entities are untouched
 */
export const DeleteBooksBookIdParams = zod.object({
  "bookId": zod.string()
})

export const DeleteBooksBookIdResponse = zod.void()


/**
 * @summary Mark the book as most recently opened
 */
export const PostBooksBookIdOpenParams = zod.object({
  "bookId": zod.string()
})

export const PostBooksBookIdOpenResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional(),
  "lastOpenedAt": zod.iso.datetime({"offset":true}).nullish()
}).optional()
})


/**
 * @summary List chapters in position order
 */
export const GetBooksBookIdChaptersParams = zod.object({
  "bookId": zod.string()
})

export const GetBooksBookIdChaptersResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "bookId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional(),
  "content": zod.looseObject({

}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})).optional()
})


/**
 * @summary Add a chapter at the end
 */
export const PostBooksBookIdChaptersParams = zod.object({
  "bookId": zod.string()
})




export const PostBooksBookIdChaptersBody = zod.object({
  "name": zod.string().min(1)
})

export const PostBooksBookIdChaptersResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "bookId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional(),
  "content": zod.looseObject({

}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}).optional()
})


/**
 * @summary Get a chapter
 */
export const GetBooksBookIdChaptersChapterIdParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string()
})

export const GetBooksBookIdChaptersChapterIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "bookId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional(),
  "content": zod.looseObject({

}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}).optional()
})


/**
 * @summary Update a chapter name and/or content
 */
export const PatchBooksBookIdChaptersChapterIdParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string()
})




export const PatchBooksBookIdChaptersChapterIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "content": zod.looseObject({

}).optional().describe('TipTap JSON document')
})

export const PatchBooksBookIdChaptersChapterIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "bookId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional(),
  "content": zod.looseObject({

}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
}).optional()
})


/**
 * @summary Delete a chapter
 */
export const DeleteBooksBookIdChaptersChapterIdParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string()
})

export const DeleteBooksBookIdChaptersChapterIdResponse = zod.void()


/**
 * @summary Move a chapter up or down within its book
 */
export const PostBooksBookIdChaptersChapterIdMoveParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string()
})

export const PostBooksBookIdChaptersChapterIdMoveBody = zod.object({
  "direction": zod.enum(['up', 'down'])
})

export const PostBooksBookIdChaptersChapterIdMoveResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "bookId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional(),
  "content": zod.looseObject({

}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}).optional(),
  "updatedAt": zod.iso.datetime({"offset":true}).optional()
})).optional()
})


/**
 * @summary List a chapter's important points
 */
export const GetBooksBookIdChaptersChapterIdImportantPointsParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string()
})

export const GetBooksBookIdChaptersChapterIdImportantPointsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "chapterId": zod.string().optional(),
  "content": zod.string().optional(),
  "position": zod.int().optional()
})).optional()
})


/**
 * @summary Add an important point
 */
export const PostBooksBookIdChaptersChapterIdImportantPointsParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string()
})




export const PostBooksBookIdChaptersChapterIdImportantPointsBody = zod.object({
  "content": zod.string().min(1)
})

export const PostBooksBookIdChaptersChapterIdImportantPointsResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "chapterId": zod.string().optional(),
  "content": zod.string().optional(),
  "position": zod.int().optional()
}).optional()
})


/**
 * @summary Delete an important point
 */
export const DeleteBooksBookIdChaptersChapterIdImportantPointsPointIdParams = zod.object({
  "bookId": zod.string(),
  "chapterId": zod.string(),
  "pointId": zod.string()
})

export const DeleteBooksBookIdChaptersChapterIdImportantPointsPointIdResponse = zod.void()


/**
 * @summary List characters in the world
 */
export const GetWorldsWorldIdCharactersParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdCharactersResponse = zod.object({
  "data": zod.array(zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "age": zod.int().nullish(),
  "health": zod.string().nullish(),
  "distinctions": zod.string().nullish(),
  "traits": zod.string().nullish(),
  "mutations": zod.string().nullish(),
  "status": zod.enum(['alive', 'dead']).optional(),
  "notes": zod.string().nullish()
})).optional()
})


/**
 * @summary Create a character
 */
export const PostWorldsWorldIdCharactersParams = zod.object({
  "worldId": zod.string()
})


export const postWorldsWorldIdCharactersBodyAgeMin = 0;



export const PostWorldsWorldIdCharactersBody = zod.object({
  "name": zod.string().min(1),
  "age": zod.int().min(postWorldsWorldIdCharactersBodyAgeMin).nullish(),
  "health": zod.string().nullish(),
  "distinctions": zod.string().nullish(),
  "traits": zod.string().nullish(),
  "mutations": zod.string().nullish(),
  "status": zod.enum(['alive', 'dead']).optional(),
  "notes": zod.string().nullish()
})

export const PostWorldsWorldIdCharactersResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "age": zod.int().nullish(),
  "health": zod.string().nullish(),
  "distinctions": zod.string().nullish(),
  "traits": zod.string().nullish(),
  "mutations": zod.string().nullish(),
  "status": zod.enum(['alive', 'dead']).optional(),
  "notes": zod.string().nullish()
}).optional()
})


/**
 * @summary Update a character; deleting one removes their timelines and relationship nodes
 */
export const PatchCharactersEntityIdParams = zod.object({
  "entityId": zod.string()
})


export const patchCharactersEntityIdBodyAgeMin = 0;



export const PatchCharactersEntityIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "age": zod.int().min(patchCharactersEntityIdBodyAgeMin).nullish(),
  "health": zod.string().nullish(),
  "distinctions": zod.string().nullish(),
  "traits": zod.string().nullish(),
  "mutations": zod.string().nullish(),
  "status": zod.enum(['alive', 'dead']).optional(),
  "notes": zod.string().nullish()
})

export const PatchCharactersEntityIdResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "age": zod.int().nullish(),
  "health": zod.string().nullish(),
  "distinctions": zod.string().nullish(),
  "traits": zod.string().nullish(),
  "mutations": zod.string().nullish(),
  "status": zod.enum(['alive', 'dead']).optional(),
  "notes": zod.string().nullish()
}).optional()
})


/**
 * @summary Delete a character
 */
export const DeleteCharactersEntityIdParams = zod.object({
  "entityId": zod.string()
})

export const DeleteCharactersEntityIdResponse = zod.void()


/**
 * @summary List places
 */
export const GetWorldsWorldIdPlacesParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdPlacesResponse = zod.object({
  "data": zod.array(zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.string().nullish(),
  "lastChapterId": zod.string().nullish()
})).optional()
})


/**
 * @summary Create a place
 */
export const PostWorldsWorldIdPlacesParams = zod.object({
  "worldId": zod.string()
})




export const PostWorldsWorldIdPlacesBody = zod.object({
  "name": zod.string().min(1),
  "status": zod.string().nullish().describe('Free text; presets include Booming'),
  "lastChapterId": zod.string().nullish()
})

export const PostWorldsWorldIdPlacesResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.string().nullish(),
  "lastChapterId": zod.string().nullish()
}).optional()
})


export const PatchPlacesEntityIdParams = zod.object({
  "entityId": zod.string()
})




export const PatchPlacesEntityIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "status": zod.string().nullish(),
  "lastChapterId": zod.string().nullish()
})

export const PatchPlacesEntityIdResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.string().nullish(),
  "lastChapterId": zod.string().nullish()
}).optional()
})


export const DeletePlacesEntityIdParams = zod.object({
  "entityId": zod.string()
})

export const DeletePlacesEntityIdResponse = zod.void()


/**
 * @summary List items
 */
export const GetWorldsWorldIdItemsParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdItemsResponse = zod.object({
  "data": zod.array(zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.string().nullish(),
  "power": zod.string().nullish(),
  "wielderEntityId": zod.string().nullish(),
  "manualWielderName": zod.string().nullish()
})).optional()
})


/**
 * @summary Create an item; wielder is either an existing world character or a manual name
 */
export const PostWorldsWorldIdItemsParams = zod.object({
  "worldId": zod.string()
})




export const PostWorldsWorldIdItemsBody = zod.object({
  "name": zod.string().min(1),
  "status": zod.string().nullish().describe('Free text; presets include Functional'),
  "power": zod.string().nullish(),
  "wielderEntityId": zod.string().nullish(),
  "manualWielderName": zod.string().nullish()
})

export const PostWorldsWorldIdItemsResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.string().nullish(),
  "power": zod.string().nullish(),
  "wielderEntityId": zod.string().nullish(),
  "manualWielderName": zod.string().nullish()
}).optional()
})


export const PatchItemsEntityIdParams = zod.object({
  "entityId": zod.string()
})




export const PatchItemsEntityIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "status": zod.string().nullish(),
  "power": zod.string().nullish(),
  "wielderEntityId": zod.string().nullish(),
  "manualWielderName": zod.string().nullish()
})

export const PatchItemsEntityIdResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "status": zod.string().nullish(),
  "power": zod.string().nullish(),
  "wielderEntityId": zod.string().nullish(),
  "manualWielderName": zod.string().nullish()
}).optional()
})


export const DeleteItemsEntityIdParams = zod.object({
  "entityId": zod.string()
})

export const DeleteItemsEntityIdResponse = zod.void()


/**
 * @summary List custom section types (at most 10 per world)
 */
export const GetWorldsWorldIdCustomEntityTypesParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdCustomEntityTypesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional()
})).optional()
})


/**
 * @summary Create a custom section type
 */
export const PostWorldsWorldIdCustomEntityTypesParams = zod.object({
  "worldId": zod.string()
})


export const postWorldsWorldIdCustomEntityTypesBodyPositionMin = 0;



export const PostWorldsWorldIdCustomEntityTypesBody = zod.object({
  "name": zod.string().min(1),
  "position": zod.int().min(postWorldsWorldIdCustomEntityTypesBodyPositionMin).optional()
})

export const PostWorldsWorldIdCustomEntityTypesResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional()
}).optional()
})


/**
 * @summary Get a custom section type with its attribute definitions
 */
export const GetCustomEntityTypesTypeIdParams = zod.object({
  "typeId": zod.string()
})

export const GetCustomEntityTypesTypeIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional(),
  "attributes": zod.array(zod.object({
  "id": zod.string().optional(),
  "entityTypeId": zod.string().optional(),
  "name": zod.string().optional(),
  "fieldType": zod.enum(['text', 'number', 'boolean', 'date', 'select', 'multiselect']).optional(),
  "required": zod.boolean().optional(),
  "position": zod.int().optional(),
  "options": zod.array(zod.string()).nullish()
})).optional()
}).optional()
})


export const PatchCustomEntityTypesTypeIdParams = zod.object({
  "typeId": zod.string()
})


export const patchCustomEntityTypesTypeIdBodyPositionMin = 0;



export const PatchCustomEntityTypesTypeIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "position": zod.int().min(patchCustomEntityTypesTypeIdBodyPositionMin).optional()
})

export const PatchCustomEntityTypesTypeIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "name": zod.string().optional(),
  "position": zod.int().optional()
}).optional()
})


export const DeleteCustomEntityTypesTypeIdParams = zod.object({
  "typeId": zod.string()
})

export const DeleteCustomEntityTypesTypeIdResponse = zod.void()


/**
 * @summary List the attribute definitions of a custom section type
 */
export const GetCustomEntityTypesTypeIdAttributesParams = zod.object({
  "typeId": zod.string()
})

export const GetCustomEntityTypesTypeIdAttributesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "entityTypeId": zod.string().optional(),
  "name": zod.string().optional(),
  "fieldType": zod.enum(['text', 'number', 'boolean', 'date', 'select', 'multiselect']).optional(),
  "required": zod.boolean().optional(),
  "position": zod.int().optional(),
  "options": zod.array(zod.string()).nullish()
})).optional()
})


/**
 * @summary Add a typed attribute to a custom section type
 */
export const PostCustomEntityTypesTypeIdAttributesParams = zod.object({
  "typeId": zod.string()
})


export const postCustomEntityTypesTypeIdAttributesBodyRequiredDefault = false;
export const postCustomEntityTypesTypeIdAttributesBodyPositionMin = 0;



export const PostCustomEntityTypesTypeIdAttributesBody = zod.object({
  "name": zod.string().min(1),
  "fieldType": zod.enum(['text', 'number', 'boolean', 'date', 'select', 'multiselect']),
  "required": zod.boolean().default(postCustomEntityTypesTypeIdAttributesBodyRequiredDefault),
  "position": zod.int().min(postCustomEntityTypesTypeIdAttributesBodyPositionMin).optional(),
  "options": zod.array(zod.string()).nullish()
})

export const PostCustomEntityTypesTypeIdAttributesResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "entityTypeId": zod.string().optional(),
  "name": zod.string().optional(),
  "fieldType": zod.enum(['text', 'number', 'boolean', 'date', 'select', 'multiselect']).optional(),
  "required": zod.boolean().optional(),
  "position": zod.int().optional(),
  "options": zod.array(zod.string()).nullish()
}).optional()
})


/**
 * @summary List custom entities in the world
 */
export const GetWorldsWorldIdCustomEntitiesParams = zod.object({
  "worldId": zod.string()
})

export const GetWorldsWorldIdCustomEntitiesResponse = zod.object({
  "data": zod.array(zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "entityTypeId": zod.string().optional(),
  "attributes": zod.record(zod.string(), zod.unknown()).optional()
})).optional()
})


/**
 * @summary Create a custom entity
 */
export const PostWorldsWorldIdCustomEntitiesParams = zod.object({
  "worldId": zod.string()
})




export const PostWorldsWorldIdCustomEntitiesBody = zod.object({
  "entityTypeId": zod.string(),
  "name": zod.string().min(1),
  "attributes": zod.record(zod.string(), zod.unknown()).optional()
})

export const PostWorldsWorldIdCustomEntitiesResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "entityTypeId": zod.string().optional(),
  "attributes": zod.record(zod.string(), zod.unknown()).optional()
}).optional()
})


export const PatchCustomEntitiesEntityIdParams = zod.object({
  "entityId": zod.string()
})




export const PatchCustomEntitiesEntityIdBody = zod.object({
  "name": zod.string().min(1).optional(),
  "attributes": zod.record(zod.string(), zod.unknown()).optional()
})

export const PatchCustomEntitiesEntityIdResponse = zod.object({
  "data": zod.object({
  "entityId": zod.string().optional(),
  "name": zod.string().optional(),
  "entityTypeId": zod.string().optional(),
  "attributes": zod.record(zod.string(), zod.unknown()).optional()
}).optional()
})


export const DeleteCustomEntitiesEntityIdParams = zod.object({
  "entityId": zod.string()
})

export const DeleteCustomEntitiesEntityIdResponse = zod.void()


/**
 * @summary List relationships in the world
 */
export const GetWorldsWorldIdRelationshipsParams = zod.object({
  "worldId": zod.string()
})

export const getWorldsWorldIdRelationshipsResponseDataItemSentimentMin = 0;
export const getWorldsWorldIdRelationshipsResponseDataItemSentimentMax = 100;



export const GetWorldsWorldIdRelationshipsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "entityAId": zod.string().optional(),
  "entityBId": zod.string().optional(),
  "relationshipType": zod.string().optional(),
  "sentiment": zod.int().min(getWorldsWorldIdRelationshipsResponseDataItemSentimentMin).max(getWorldsWorldIdRelationshipsResponseDataItemSentimentMax).optional()
})).optional()
})


/**
 * @summary Create a relationship between two world entities
 */
export const PostWorldsWorldIdRelationshipsParams = zod.object({
  "worldId": zod.string()
})


export const postWorldsWorldIdRelationshipsBodySentimentDefault = 50;
export const postWorldsWorldIdRelationshipsBodySentimentMin = 0;
export const postWorldsWorldIdRelationshipsBodySentimentMax = 100;



export const PostWorldsWorldIdRelationshipsBody = zod.object({
  "entityAId": zod.string(),
  "entityBId": zod.string(),
  "relationshipType": zod.string().min(1).describe('Free text; presets include Partner'),
  "sentiment": zod.int().min(postWorldsWorldIdRelationshipsBodySentimentMin).max(postWorldsWorldIdRelationshipsBodySentimentMax).default(postWorldsWorldIdRelationshipsBodySentimentDefault)
})

export const postWorldsWorldIdRelationshipsResponseDataSentimentMin = 0;
export const postWorldsWorldIdRelationshipsResponseDataSentimentMax = 100;



export const PostWorldsWorldIdRelationshipsResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "entityAId": zod.string().optional(),
  "entityBId": zod.string().optional(),
  "relationshipType": zod.string().optional(),
  "sentiment": zod.int().min(postWorldsWorldIdRelationshipsResponseDataSentimentMin).max(postWorldsWorldIdRelationshipsResponseDataSentimentMax).optional()
}).optional()
})


export const PatchRelationshipsRelationshipIdParams = zod.object({
  "relationshipId": zod.string()
})


export const patchRelationshipsRelationshipIdBodySentimentMin = 0;
export const patchRelationshipsRelationshipIdBodySentimentMax = 100;



export const PatchRelationshipsRelationshipIdBody = zod.object({
  "relationshipType": zod.string().min(1).optional(),
  "sentiment": zod.int().min(patchRelationshipsRelationshipIdBodySentimentMin).max(patchRelationshipsRelationshipIdBodySentimentMax).optional()
})

export const patchRelationshipsRelationshipIdResponseDataSentimentMin = 0;
export const patchRelationshipsRelationshipIdResponseDataSentimentMax = 100;



export const PatchRelationshipsRelationshipIdResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "worldId": zod.string().optional(),
  "entityAId": zod.string().optional(),
  "entityBId": zod.string().optional(),
  "relationshipType": zod.string().optional(),
  "sentiment": zod.int().min(patchRelationshipsRelationshipIdResponseDataSentimentMin).max(patchRelationshipsRelationshipIdResponseDataSentimentMax).optional()
}).optional()
})


export const DeleteRelationshipsRelationshipIdParams = zod.object({
  "relationshipId": zod.string()
})

export const DeleteRelationshipsRelationshipIdResponse = zod.void()


/**
 * @summary List a character's per-book timelines
 */
export const GetCharactersEntityIdTimelinesParams = zod.object({
  "entityId": zod.string()
})

export const GetCharactersEntityIdTimelinesResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "characterEntityId": zod.string().optional(),
  "bookId": zod.string().optional()
})).optional()
})


/**
 * @summary Attach the character to a book
 */
export const PostCharactersEntityIdTimelinesParams = zod.object({
  "entityId": zod.string()
})

export const PostCharactersEntityIdTimelinesBody = zod.object({
  "bookId": zod.string()
})

export const PostCharactersEntityIdTimelinesResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "characterEntityId": zod.string().optional(),
  "bookId": zod.string().optional()
}).optional()
})


/**
 * @summary List timeline points
 */
export const GetCharactersEntityIdTimelinesTimelineIdPointsParams = zod.object({
  "entityId": zod.string(),
  "timelineId": zod.string()
})

export const GetCharactersEntityIdTimelinesTimelineIdPointsResponse = zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "timelineId": zod.string().optional(),
  "content": zod.string().optional(),
  "position": zod.int().optional(),
  "chapterId": zod.string().nullish()
})).optional()
})


/**
 * @summary Add a timeline point
 */
export const PostCharactersEntityIdTimelinesTimelineIdPointsParams = zod.object({
  "entityId": zod.string(),
  "timelineId": zod.string()
})




export const PostCharactersEntityIdTimelinesTimelineIdPointsBody = zod.object({
  "content": zod.string().min(1),
  "chapterId": zod.string().nullish()
})

export const PostCharactersEntityIdTimelinesTimelineIdPointsResponse = zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "timelineId": zod.string().optional(),
  "content": zod.string().optional(),
  "position": zod.int().optional(),
  "chapterId": zod.string().nullish()
}).optional()
})


export const DeleteCharactersEntityIdTimelinesTimelineIdPointsPointIdParams = zod.object({
  "entityId": zod.string(),
  "timelineId": zod.string(),
  "pointId": zod.string()
})

export const DeleteCharactersEntityIdTimelinesTimelineIdPointsPointIdResponse = zod.void()
